frequency: 50
two_d_mode: true
publish_tf: false

odom_frame: odom
base_link_frame: base_link

odom0: /wheel_encoder_odom   #odom source for respective robot
odom0_config: [true, false, false,
               false, false, false,
               true, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_relative: true

imu0: /imu/data #imu source for respective bot
imu0_config: [false, false, false,
              true, true, true,
              true, true, true,
              false, false, false,
              true, true, true]
imu0_differential: false
imu0_relative: true
